# Generated by Django 4.2.13 on 2024-06-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='id_user',
            new_name='user',
        ),
    ]
