# Generated by Django 4.2.13 on 2024-06-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_id_user_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
