# Generated by Django 4.2.13 on 2024-06-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Ingreso', 'ingreso'), ('Gasto', 'gasto')], default='Ingreso', max_length=7),
        ),
    ]
