# Generated by Django 4.2.13 on 2024-06-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_saving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='EFECTIVO', max_length=10),
        ),
    ]
